name: CI

# Specify which GitHub events will trigger a CI build
on: push

# Define a job 'build'
jobs:

  build:

    # Specify the OS to run tests on
    runs-on: ubuntu-latest

    # A job is a sequence of steps
    steps:

    # Check out repository and set up Python
    # A 'name' is an optional label shown in the log
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
